// You are given two strings, s and t which only consist of lowercase letters. t is generated by shuffling the letters in s as well as potentially adding an additional random character. Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
// Note: You may assume that at most one additional character can be added to t.

// Ex: Given the following strings...

// s = "foobar", t = "barfoot", return 't'
// s = "ide", t = "idea", return 'a'
// s = "coding", t "ingcod", return ''


function findDiff(str1, str2){ 
    var s1 = str1.split('');
    var s2 = str2.split('');

    if (s1.length > s2.length) {
      var difference = s1.filter(x => !s2.includes(x));
    } else {
      var difference = s2.filter(x => !s1.includes(x));
    }
    return difference.toString();
}
findDiff('foobar','barfoot');